import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { KeyRound, RefreshCw, AlertTriangle, ShieldCheck } from 'lucide-react';
import { encryptionApi, type EncryptionOverview } from '../../services/api';
import clsx from 'clsx';

/**
 * The key that protects stored credentials (outside review P2-29): where it
 * comes from, what is stored under it, and a rotation that keeps the old key
 * until everything has moved to the new one. Admin only.
 */
export default function EncryptionKeyCard() {
  const qc = useQueryClient();
  const [message, setMessage] = useState<{ tone: 'ok' | 'error'; text: string } | null>(null);
  const [confirmRotate, setConfirmRotate] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ['encryption-overview'],
    queryFn: () => encryptionApi.overview().then((r) => r.data),
  });

  const done = (res: { data: EncryptionOverview & { message: string } }) => {
    qc.setQueryData(['encryption-overview'], res.data);
    setMessage({ tone: 'ok', text: res.data.message });
    setConfirmRotate(false);
  };
  const failed = (err: unknown) =>
    setMessage({ tone: 'error', text: (err as { response?: { data?: { error?: string } } })?.response?.data?.error || 'Failed' });

  const rotate = useMutation({ mutationFn: () => encryptionApi.rotate(), onSuccess: done, onError: failed });
  const reencrypt = useMutation({ mutationFn: () => encryptionApi.reencrypt(), onSuccess: done, onError: failed });
  const retire = useMutation({ mutationFn: () => encryptionApi.retire(), onSuccess: done, onError: failed });
  const busy = rotate.isPending || reencrypt.isPending || retire.isPending;

  return (
    <div className="card p-5 space-y-3">
      <h3 className="font-semibold text-gray-900 dark:text-white flex items-center gap-2">
        <KeyRound className="w-4 h-4 text-blue-500" /> Encryption key
      </h3>
      <p className="text-xs text-gray-500 dark:text-slate-400">
        Device passwords, credential presets, SSH keys, the SSO client secret and backups that contain secrets are
        encrypted with this key. Keep a copy of it apart from your database backups: a database without its key
        can&apos;t be decrypted.
      </p>

      {isLoading || !data ? (
        <div className="text-sm text-gray-400 flex items-center gap-2"><RefreshCw className="w-4 h-4 animate-spin" /> Checking…</div>
      ) : (
        <>
          {data.key_missing && (
            <div className="p-3 rounded-lg border border-red-300 bg-red-50 dark:bg-red-900/20 dark:border-red-800 text-sm text-red-800 dark:text-red-300 flex gap-2">
              <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
              <span>
                {data.totals.unreadable} stored value(s) can&apos;t be decrypted with any known key. Restore
                {' '}<code>secrets.json</code> to the <code>app_data</code> volume, or set <code>ENCRYPTION_KEY</code>
                {' '}(or <code>ENCRYPTION_KEY_PREVIOUS</code>) to the original key, and restart.
              </span>
            </div>
          )}

          <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-1 text-sm">
            <dt className="text-gray-500 dark:text-slate-400">Source</dt>
            <dd className="text-gray-900 dark:text-white">
              {data.source === 'env' ? 'ENCRYPTION_KEY in .env' : 'Generated by the manager (app_data/secrets.json)'}
            </dd>
            <dt className="text-gray-500 dark:text-slate-400">Key ID</dt>
            <dd className="font-mono text-gray-900 dark:text-white" title="A fingerprint of the key, not the key">{data.key_id}</dd>
            <dt className="text-gray-500 dark:text-slate-400">Older keys kept</dt>
            <dd className="text-gray-900 dark:text-white">
              {data.saved_previous_keys + data.env_previous_keys}
              {data.env_previous_keys > 0 && <span className="text-xs text-gray-500"> ({data.env_previous_keys} from ENCRYPTION_KEY_PREVIOUS)</span>}
            </dd>
          </dl>

          {data.locations.length > 0 && (
            <table className="w-full text-xs">
              <thead className="text-gray-500 dark:text-slate-400">
                <tr><th className="text-left font-medium py-1">Stored</th><th className="text-right font-medium">Current key</th><th className="text-right font-medium">Older key</th><th className="text-right font-medium">Unreadable</th></tr>
              </thead>
              <tbody className="text-gray-900 dark:text-white">
                {data.locations.map((l) => (
                  <tr key={l.location} className="border-t border-gray-100 dark:border-slate-700/50">
                    <td className="py-1">{l.location}</td>
                    <td className="text-right">{l.current}</td>
                    <td className={clsx('text-right', l.old > 0 && 'text-amber-600')}>{l.old}</td>
                    <td className={clsx('text-right', l.unreadable > 0 && 'text-red-600 font-semibold')}>{l.unreadable}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          {data.totals.old === 0 && data.totals.unreadable === 0 && !data.key_missing && (
            <p className="text-xs text-green-700 dark:text-green-400 flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5" /> Everything is encrypted with the current key.
            </p>
          )}

          <div className="flex flex-wrap gap-2">
            {data.source === 'env' ? (
              <p className="text-xs text-gray-500 dark:text-slate-400">
                To rotate a key set in <code>.env</code>: set <code>ENCRYPTION_KEY</code> to the new key and
                {' '}<code>ENCRYPTION_KEY_PREVIOUS</code> to the old one, restart, then remove
                {' '}<code>ENCRYPTION_KEY_PREVIOUS</code> once nothing shows under an older key.
              </p>
            ) : confirmRotate ? (
              <>
                <span className="text-xs text-gray-600 dark:text-slate-300 self-center">
                  A new key is generated and everything is re-encrypted with it. The old key is kept until you retire it.
                </span>
                <button onClick={() => rotate.mutate()} disabled={busy} className="btn-primary text-xs py-1.5 flex items-center gap-1.5">
                  {rotate.isPending && <RefreshCw className="w-3.5 h-3.5 animate-spin" />} Rotate now
                </button>
                <button onClick={() => setConfirmRotate(false)} disabled={busy} className="btn-secondary text-xs py-1.5">Cancel</button>
              </>
            ) : (
              <button onClick={() => { setMessage(null); setConfirmRotate(true); }} disabled={busy || !data.can_rotate}
                className="btn-secondary text-xs py-1.5">Rotate key…</button>
            )}
            {data.totals.old > 0 && (
              <button onClick={() => reencrypt.mutate()} disabled={busy} className="btn-secondary text-xs py-1.5 flex items-center gap-1.5">
                {reencrypt.isPending && <RefreshCw className="w-3.5 h-3.5 animate-spin" />} Re-encrypt with the current key
              </button>
            )}
            {data.can_retire && (
              <button onClick={() => retire.mutate()} disabled={busy} className="btn-secondary text-xs py-1.5 flex items-center gap-1.5">
                {retire.isPending && <RefreshCw className="w-3.5 h-3.5 animate-spin" />} Retire older keys
              </button>
            )}
          </div>

          {message && (
            <p className={clsx('text-xs', message.tone === 'ok' ? 'text-green-700 dark:text-green-400' : 'text-red-600 dark:text-red-400')}>
              {message.text}
            </p>
          )}
        </>
      )}
    </div>
  );
}
